module.exports = {
  disableEmoji: false,
  format: "{type}{scope}: {emoji}{subject}",
  list: [
    "wip",
    "feat",
    "test",
    "fix",
    "lint",
    "upgrade",
    "downgrade",
    "product",
    "backend",
    "chore",
    "docs",
    "refactor",
    "style",
    "ci",
    "perf",
    "release",
  ],
  maxMessageLength: 64,
  minMessageLength: 3,
  questions: [
    "type",
    "scope",
    "subject",
    "body",
    "breaking",
    "issues",
    "lerna",
  ],
  scopes: [],
  types: {
    wip: {
      description: "work in progress",
      emoji: "🔨",
      value: "wip",
    },
    chore: {
      description: "构建过程或辅助工具更改",
      emoji: "🤖",
      value: "chore",
    },
    ci: {
      description: "CI 相关变更",
      emoji: "🎡",
      value: "ci",
    },
    docs: {
      description: "仅文档变更",
      emoji: "📝",
      value: "docs",
    },
    feat: {
      description: "新功能",
      emoji: "✨",
      value: "feat",
    },
    fix: {
      description: "Bug 修复",
      emoji: "🐛",
      value: "fix",
    },
    perf: {
      description: "性能优化",
      emoji: "⚡️",
      value: "perf",
    },
    refactor: {
      description: "既不修复 bug 也不添加功能的代码更改",
      emoji: "💡",
      value: "refactor",
    },
    release: {
      description: "创建一个 release",
      emoji: "🏹",
      value: "release",
    },
    style: {
      description: "代码风格变更：Markup, 空白、格式、缺少分号等",
      emoji: "💄",
      value: "style",
    },
    test: {
      description: "添加测试用例",
      emoji: "✅",
      value: "test",
    },
    backend: {
      description: "后端修改导致的变更",
      emoji: "💽",
      value: "backend",
    },
    product: {
      description: "产品修改导致的变更",
      emoji: "📎",
      value: "product",
    },
    lint: {
      description: "修复 lint 警告",
      emoji: "🚨",
      value: "lint",
    },
    upgrade: {
      description: "依赖更新",
      emoji: "⬆️",
      value: "upgrade",
    },
    downgrade: {
      description: "依赖降级",
      emoji: "⬇️",
      value: "downgrade",
    },
  },
};
