// Automatically generated by script, please do not modify this file manually.
// program-path\config\config.yaml
export interface Config {
  port: number;
  globalPrefix: string;
  swaggerPath: string;
}
