// Automatically generated by script, please do not modify this file manually.
// program-path\package.json
export interface PkgJSON {
  name: string;
  version: string;
  description: string;
  author: string;
  private: boolean;
  license: string;
  scripts: Scripts;
  dependencies: Dependencies;
  devDependencies: DevDependencies;
  jest: Jest;
  'lint-staged': LintStaged;
  config: Config;
  _moduleAliases: ModuleAliases;
  packageManager: string;
}

export interface ModuleAliases {
  '@root': string;
  '~types': string;
  '@': string;
}

export interface Config {
  commitizen: Commitizen;
}

export interface Commitizen {
  path: string;
}

export interface Dependencies {
  '@nestjs/common': string;
  '@nestjs/config': string;
  '@nestjs/core': string;
  '@nestjs/jwt': string;
  '@nestjs/passport': string;
  '@nestjs/platform-express': string;
  '@nestjs/swagger': string;
  '@nestjs/typeorm': string;
  helmet: string;
  'js-yaml': string;
  lodash: string;
  'module-alias': string;
  mysql2: string;
  passport: string;
  'passport-jwt': string;
  'passport-local': string;
  pg: string;
  'quicktype-core': string;
  'reflect-metadata': string;
  rxjs: string;
  typeorm: string;
  uuid: string;
}

export interface DevDependencies {
  '@commitlint/cli': string;
  '@commitlint/config-conventional': string;
  '@nestjs/cli': string;
  '@nestjs/schematics': string;
  '@nestjs/testing': string;
  '@types/express': string;
  '@types/jest': string;
  '@types/js-yaml': string;
  '@types/lodash': string;
  '@types/node': string;
  '@types/passport-jwt': string;
  '@types/passport-local': string;
  '@types/supertest': string;
  '@types/uuid': string;
  '@typescript-eslint/eslint-plugin': string;
  '@typescript-eslint/parser': string;
  'cross-env': string;
  eslint: string;
  'eslint-config-prettier': string;
  'eslint-plugin-prettier': string;
  'git-cz': string;
  husky: string;
  jest: string;
  prettier: string;
  'source-map-support': string;
  supertest: string;
  'ts-jest': string;
  'ts-loader': string;
  'ts-node': string;
  'tsconfig-paths': string;
  typescript: string;
  webpack: string;
}

export interface Jest {
  moduleFileExtensions: string[];
  rootDir: string;
  testRegex: string;
  transform: Transform;
  collectCoverageFrom: string[];
  coverageDirectory: string;
  testEnvironment: string;
}

export interface Transform {
  '^.+\\.(t|j)s$': string;
}

export interface LintStaged {
  '**/*.{js,ts,json}': string[];
}

export interface Scripts {
  postinstall: string;
  cz: string;
  build: string;
  format: string;
  start: string;
  'start:dev': string;
  'start:debug': string;
  'start:prod': string;
  lint: string;
  test: string;
  'test:watch': string;
  'test:cov': string;
  'test:debug': string;
  'test:e2e': string;
  types: string;
}
