# 端口
port: 5000
# 全局前缀
globalPrefix: api
# swagger的路径
swaggerPath: swagger
# 数据库相关配置
db:
  # mysql2/pg
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: Aa123456
  database: leaby
jwt:
  # jwt 的 secret，如果是 auto 则会在每次系统启动时重新生成，建议填入一个自生成的 uuid
  secret: auto
# reCAPTCHA 的 token
# @see https://developers.google.com/recaptcha/docs/verify?hl=zh-cn
#recaptcha:
