# 端口
port: 3000
# 全局前缀
globalPrefix: api
# swagger的路径
swaggerPath: swagger
# 数据库相关配置
db:
  # mysql2/pg
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: Aa123456
  database: leaby
